## Task
Explore NumPy basics

## Notebook Summary
* Array data types
* where, select, choose, nonzero

## References
* *Python for Data Analysis*, Wes McKinney, O'Reilly, 2012
* *Numerical Python*, Robert Johansson, APress, 2015
* *Python Data Science Handbook*, Jake VanderPlas, O'Reilly, 2016


In [3]:
# display output from all cmds just like Python shell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import platform
print 'python.version = ', platform.python_version()
import IPython
print 'ipython.version =', IPython.version_info

import numpy as np
print 'numpy.version = ', np.__version__


python.version =  2.7.10
ipython.version = (5, 1, 0, '')
numpy.version =  1.11.3


In [79]:
# Array data types

np.ones([2,3])
np.ones([2,3]).astype(int)
np.ones([2,3]).astype(str)

print '---'

np.array([3.14, 4.25, 5.36])
np.array([3.14, 4.25, 5.36]).astype(int)
np.array([3.14, 4.25, 5.36]).astype(str)

print '---'

np.array(['1','2','3','4']).astype('int')

print '---'

np.array(['1.1', '2.2', '3', '4'])
np.array(['1.1', '2.2', '3', '4']).astype(float)
np.array(['1.1', '2.2', '3', '4']).astype(str)
np.array(['1.1', '2.2', '3', '4']).astype(float).astype(int) # can't go directly from float in str to int
myarr.dtype
np.array(['1.1', '2.2', '3', '4']).astype('float').astype(myarr.dtype)


array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

array([[1, 1, 1],
       [1, 1, 1]])

array([['1.0', '1.0', '1.0'],
       ['1.0', '1.0', '1.0']], 
      dtype='|S32')

---


array([ 3.14,  4.25,  5.36])

array([3, 4, 5])

array(['3.14', '4.25', '5.36'], 
      dtype='|S32')

---


array([1, 2, 3, 4])

---


array(['1.1', '2.2', '3', '4'], 
      dtype='|S3')

array([ 1.1,  2.2,  3. ,  4. ])

array(['1.1', '2.2', '3', '4'], 
      dtype='|S3')

array([1, 2, 3, 4])

dtype('int64')

array([1, 2, 3, 4])