## Task
Explore data pre-processing in scikit-learn

## Notebook Summary
* Binarizer, `binarize`
* LabelBinarizer, `label_binarize`
* Imputer
* MaxAbsScaler
* MinMaxScaler
* Normalizer,  `normalize`
* OneHotEncoder
* PolynomialFeatures
* Standardcaler, RobustScaler
* `scale`,  `robust_scale`
* `maxabs_scale`, `minmax_scale`

## References
* [scikit-learn PreProcessing and Normalization](http://scikit-learn.org/stable/modules/classes.html#module-sklearn.preprocessing)


In [2]:
# display output from all cmds just like Python shell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

%matplotlib inline

import sklearn
from sklearn import datasets
from sklearn import preprocessing as pp
import matplotlib.pyplot as p
import numpy as np

print 'sklearn version = {}'.format(sklearn.__version__)

sklearn version = 0.18.1


In [5]:
iris = datasets.load_iris()
dir(iris)
iris.data.shape

print '----- Features'
iris.feature_names
type(iris.feature_names)

print '----- Target'
iris.target_names
type(iris.target_names)


['DESCR', 'data', 'feature_names', 'target', 'target_names']

(150, 4)

----- Features


['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

list

----- Target


array(['setosa', 'versicolor', 'virginica'], 
      dtype='|S10')

numpy.ndarray

In [53]:
x, y = iris.data, iris.target
print type(x)
x[0:5,:]

print type(y)
y[0:5]

<type 'numpy.ndarray'>


array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])

<type 'numpy.ndarray'>


array([0, 0, 0, 0, 0])

In [43]:
x_scaled = pp.scale(x)
type(x_scaled)
x_scaled.shape
x_scaled[0:5,:]

numpy.ndarray

(150, 4)

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

In [49]:
x.mean(axis=0)
x.std(axis=0)


array([ 5.84333333,  3.054     ,  3.75866667,  1.19866667])

array([ 0.82530129,  0.43214658,  1.75852918,  0.76061262])

1.0

0.81649658092772603

In [52]:
x_normed = pp.normalize(x)
type(x_normed)
x_normed.shape
x_normed[0:5,:]


numpy.ndarray

(150, 4)

array([[ 0.80377277,  0.55160877,  0.22064351,  0.0315205 ],
       [ 0.82813287,  0.50702013,  0.23660939,  0.03380134],
       [ 0.80533308,  0.54831188,  0.2227517 ,  0.03426949],
       [ 0.80003025,  0.53915082,  0.26087943,  0.03478392],
       [ 0.790965  ,  0.5694948 ,  0.2214702 ,  0.0316386 ]])