## Task
Explore NumPy basics

## Notebook Summary
* Creating arrays
 * array(), asarray()
 * zeroes(), ones(), full(), fill(), empty(), eye(), identity(), diag()
 * arange(), linspace(), logspace(), fromfunction()
* Array data types
* Basic indexing
* Boolean indexing
* Fancy indexing
* Transposing
* Ravel, flatten
* Meshgrid
* where, select, choose, nonzero
* Random walks
* Matrix products - dot, inner, cross, outer, kron, einsum, tensordot
* [Sorting](#sorting)

## References
* *Python for Data Analysis*, Wes McKinney, O'Reilly, 2012
* *Numerical Python*, Robert Johansson, APress, 2015


In [3]:
# display output from all cmds just like Python shell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import platform
print 'python.version = ', platform.python_version()
import IPython
print 'ipython.version =', IPython.version_info

import numpy as np
print 'numpy.version = ', np.__version__


python.version =  2.7.10
ipython.version = (5, 1, 0, '')
numpy.version =  1.11.3


In [76]:
# Creating arrays from lists using array() & asarray()

mylist = [1,2,3,4]
mylist
myarr = np.array(mylist) 
myarr
myarr.dtype

print '---'

myarr = np.array([[5.1,6.2],[7.3,8.4]])
myarr
myarr.dtype

myarr2 = np.array(myarr) # copy=True by default; else copy made only if necessary
myarr2[0,1] = 999
myarr2
print 'myarr is myarr2 = ', myarr is myarr2

print '---'

mylist = [[1,2,3],[4,5,6],[7,8,9]]
mylist
myarr = np.array(mylist)
myarr
myarr.ndim
myarr.shape
myarr.size
myarr.dtype

myarr.astype(float)
myarr.astype(str)
myarr

print '---'

mylist = [1, 2, 3,4]
myarr = np.asarray(mylist) # no copy if input is an ndarray 
myarr
myarr2 = np.asarray(myarr)
print 'myarr is myarr2 = ', myarr is myarr2


[1, 2, 3, 4]

array([1, 2, 3, 4])

dtype('int64')

---


array([[ 5.1,  6.2],
       [ 7.3,  8.4]])

dtype('float64')

array([[   5.1,  999. ],
       [   7.3,    8.4]])

myarr is myarr2 =  False
---


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

2

(3, 3)

9

dtype('int64')

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '8', '9']], 
      dtype='|S21')

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

---


array([1, 2, 3, 4])

myarr is myarr2 =  True


In [119]:
# Creating arrays using zeros(), ones(), full(), fill(), empty(), eye(), identity(), diag()

myarr

print '---'

np.zeros(1, dtype='complex')
np.zeros([2,3,2])
np.zeros_like(myarr)

print '---'

np.ones(2)
np.ones([1,2,3], dtype='int')
np.ones_like(myarr)

print '---'

np.full((1,1), 9.9)
np.full([3,2], 'a', dtype='str')
np.full_like(myarr, 99, dtype='int')

print '---'

myarr2 = np.zeros([2,3])
myarr2
myarr2.fill(-50)
myarr2

print '---'

np.empty(3)
np.empty([2,3], dtype=int)
np.empty_like(myarr)

print '---'

np.eye(4)
np.eye(4,3, k=-1)
np.identity(4)

print '---'

np.diag([1,2,3])
np.diag(np.arange(10))

print '---'

np.diag(np.arange(10))[::2] # get every other row
np.diag(np.arange(10))[:,::2] # get every other row

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

---


array([ 0.+0.j])

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

---


array([ 1.,  1.])

array([[[1, 1, 1],
        [1, 1, 1]]])

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

---


array([[ 9.9]])

array([['a', 'a'],
       ['a', 'a'],
       ['a', 'a']], 
      dtype='|S1')

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])

---


array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

array([[-50., -50., -50.],
       [-50., -50., -50.]])

---


array([ 0.,  0.,  0.])

array([[0, 0, 0],
       [0, 0, 0]])

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])

---


array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

array([[ 0.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

---


array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

---


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0]])

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 8],
       [0, 0, 0, 0, 0]])

In [117]:
# Creating arrays using arange(), linspace(), logspace(), fromfunction()

np.arange(0)
np.arange(1)
np.arange(5)
np.arange(1,20,3)
np.arange(1.5,5.2,0.333)

print '---'

np.linspace(0,1)# return 50 pts by default
np.linspace(start=1, stop=10, num=10, dtype='int')
np.linspace(2,4, num=20, endpoint=False, retstep=True)
np.linspace(2,4, num=20, endpoint=True, retstep=True)

print '---'

np.logspace(1,2) # return 450 pts by default with base=10
np.logspace(1,2, num=10)
np.logspace(1,2, num=10, base=2.72)

print '---'

f = lambda x,y: np.round(np.sin(x+y),2)
np.fromfunction(f, (3,3))


array([], dtype=int64)

array([0])

array([0, 1, 2, 3, 4])

array([ 1,  4,  7, 10, 13, 16, 19])

array([ 1.5  ,  1.833,  2.166,  2.499,  2.832,  3.165,  3.498,  3.831,
        4.164,  4.497,  4.83 ,  5.163])

---


array([ 0.        ,  0.02040816,  0.04081633,  0.06122449,  0.08163265,
        0.10204082,  0.12244898,  0.14285714,  0.16326531,  0.18367347,
        0.20408163,  0.2244898 ,  0.24489796,  0.26530612,  0.28571429,
        0.30612245,  0.32653061,  0.34693878,  0.36734694,  0.3877551 ,
        0.40816327,  0.42857143,  0.44897959,  0.46938776,  0.48979592,
        0.51020408,  0.53061224,  0.55102041,  0.57142857,  0.59183673,
        0.6122449 ,  0.63265306,  0.65306122,  0.67346939,  0.69387755,
        0.71428571,  0.73469388,  0.75510204,  0.7755102 ,  0.79591837,
        0.81632653,  0.83673469,  0.85714286,  0.87755102,  0.89795918,
        0.91836735,  0.93877551,  0.95918367,  0.97959184,  1.        ])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

(array([ 2. ,  2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,
         3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9]), 0.1)

(array([ 2.        ,  2.10526316,  2.21052632,  2.31578947,  2.42105263,
         2.52631579,  2.63157895,  2.73684211,  2.84210526,  2.94736842,
         3.05263158,  3.15789474,  3.26315789,  3.36842105,  3.47368421,
         3.57894737,  3.68421053,  3.78947368,  3.89473684,  4.        ]),
 0.10526315789473684)

---


array([  10.        ,   10.48113134,   10.98541142,   11.51395399,
         12.06792641,   12.64855217,   13.25711366,   13.89495494,
         14.56348478,   15.26417967,   15.9985872 ,   16.76832937,
         17.57510625,   18.42069969,   19.30697729,   20.23589648,
         21.20950888,   22.22996483,   23.29951811,   24.42053095,
         25.59547923,   26.82695795,   28.11768698,   29.47051703,
         30.88843596,   32.37457543,   33.93221772,   35.56480306,
         37.2759372 ,   39.06939937,   40.94915062,   42.9193426 ,
         44.98432669,   47.14866363,   49.41713361,   51.79474679,
         54.28675439,   56.89866029,   59.63623317,   62.50551925,
         65.51285569,   68.6648845 ,   71.9685673 ,   75.43120063,
         79.06043211,   82.86427729,   86.85113738,   91.0298178 ,
         95.40954763,  100.        ])

array([  10.        ,   12.91549665,   16.68100537,   21.5443469 ,
         27.82559402,   35.93813664,   46.41588834,   59.94842503,
         77.42636827,  100.        ])

array([ 2.72      ,  3.03986529,  3.39734594,  3.79686543,  4.24336744,
        4.74237697,  5.30006879,  5.9233438 ,  6.61991441,  7.3984    ])

---


array([[ 0.  ,  0.84,  0.91],
       [ 0.84,  0.91,  0.14],
       [ 0.91,  0.14, -0.76]])

In [79]:
# Array data types

np.ones([2,3])
np.ones([2,3]).astype(int)
np.ones([2,3]).astype(str)

print '---'

np.array([3.14, 4.25, 5.36])
np.array([3.14, 4.25, 5.36]).astype(int)
np.array([3.14, 4.25, 5.36]).astype(str)

print '---'

np.array(['1','2','3','4']).astype('int')

print '---'

np.array(['1.1', '2.2', '3', '4'])
np.array(['1.1', '2.2', '3', '4']).astype(float)
np.array(['1.1', '2.2', '3', '4']).astype(str)
np.array(['1.1', '2.2', '3', '4']).astype(float).astype(int) # can't go directly from float in str to int
myarr.dtype
np.array(['1.1', '2.2', '3', '4']).astype('float').astype(myarr.dtype)


array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

array([[1, 1, 1],
       [1, 1, 1]])

array([['1.0', '1.0', '1.0'],
       ['1.0', '1.0', '1.0']], 
      dtype='|S32')

---


array([ 3.14,  4.25,  5.36])

array([3, 4, 5])

array(['3.14', '4.25', '5.36'], 
      dtype='|S32')

---


array([1, 2, 3, 4])

---


array(['1.1', '2.2', '3', '4'], 
      dtype='|S3')

array([ 1.1,  2.2,  3. ,  4. ])

array(['1.1', '2.2', '3', '4'], 
      dtype='|S3')

array([1, 2, 3, 4])

dtype('int64')

array([1, 2, 3, 4])

In [126]:
# Basic indexing & slicing

myarr = np.arange(10)
myarr
myarr[1]
myarr[[-3,-2,-1]]
myarr[1:6:2]
myarr[::-1] # reverse elements

print '---'

myslice = myarr[4:6] # this is a view, not a copy
myslice
myslice[:] = -999
myslice
myarr # original array is also modified

print '---'

myslice = myarr[4:6].copy()
myslice[:] = -1
myslice
myarr # original array is not modified

print '---'

myarr = np.arange(24).reshape(6,4)
myarr

myarr[5], myarr[5].shape
myarr[4:,:], myarr[4:,:].shape

print '---'

myarr[0,1]

myarr[:,1]
myarr[:,[2,3]]
myarr[:,:3], myarr[:,:3].shape

myarr2 = myarr.copy()
myarr2[:,[2,3]] = -99
myarr2

myarr[1,:]
myarr[[2,3],:]
myarr[[0,1,2],2:]
myarr[:2, 2:], myarr[:2, 2:].shape

print '---'

myarr[2,2]
myarr[2][2]

# Need to mix integer and slices to get lower dimensional slices
# See Fig 4.2 on pg 90 in 'Python for Data Analysis'


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

1

array([7, 8, 9])

array([1, 3, 5])

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

---


array([4, 5])

array([-999, -999])

array([   0,    1,    2,    3, -999, -999,    6,    7,    8,    9])

---


array([-1, -1])

array([   0,    1,    2,    3, -999, -999,    6,    7,    8,    9])

---


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

(array([20, 21, 22, 23]), (4,))

(array([[16, 17, 18, 19],
        [20, 21, 22, 23]]), (2, 4))

---


1

array([ 1,  5,  9, 13, 17, 21])

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

(array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14],
        [16, 17, 18],
        [20, 21, 22]]), (6, 3))

array([[  0,   1, -99, -99],
       [  4,   5, -99, -99],
       [  8,   9, -99, -99],
       [ 12,  13, -99, -99],
       [ 16,  17, -99, -99],
       [ 20,  21, -99, -99]])

array([4, 5, 6, 7])

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

(array([[2, 3],
        [6, 7]]), (2, 2))

---


10

10

In [125]:
# Boolean indexing - index with arrays of True & False

myarr = np.arange(20)
myarr
idx = myarr % 4 == 0
idx
myarr[idx]
myarr[myarr % 4 == 0]

print '---'

myarr = np.arange(32).reshape(8,4)
myarr

# statement below will not return 1st & 3rd cols because True, False are interpreted as 1, 0 
# resulting in myarr[:,[1,0,1,0]]
myarr[:,[True, False, True, False]] 
# instead, do this
myarr[:,np.array([True, False, True, False])]

print '---'

myarr = np.random.randn(24).reshape(6,4)
myarr[myarr<0] = 0
myarr = myarr.round(2)
myarr[1] = 7
myarr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

array([ True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False], dtype=bool)

array([ 0,  4,  8, 12, 16])

array([ 0,  4,  8, 12, 16])

---


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

/Users/vissan1/GitHub/ml/venv/lib/python2.7/site-packages/ipykernel/__main__.py:17: FutureWarning: in the future, boolean array-likes will be handled as a boolean array index


array([[ 1,  0,  1,  0],
       [ 5,  4,  5,  4],
       [ 9,  8,  9,  8],
       [13, 12, 13, 12],
       [17, 16, 17, 16],
       [21, 20, 21, 20],
       [25, 24, 25, 24],
       [29, 28, 29, 28]])

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22],
       [24, 26],
       [28, 30]])

---


array([[ 0.  ,  0.  ,  1.41,  0.51],
       [ 7.  ,  7.  ,  7.  ,  7.  ],
       [ 0.  ,  1.87,  0.  ,  0.18],
       [ 0.  ,  0.  ,  0.42,  1.77],
       [ 0.55,  0.  ,  0.33,  0.  ],
       [ 0.  ,  0.31,  0.91,  0.  ]])

In [123]:
# Fancy indexing - indexing using integer arrays / lists / seq of integers

myarr = np.arange(32).reshape(8,4)
myarr

myarr[[0,1],:]
myarr[[0,1]]
myarr[np.array([0,1])]
myarr[[1,0,1],:]

myslice = myarr[[0,1],:] # fancy indexing returns a copy, not a view
myslice[:] = 99
myslice
myarr
myarr[[0,1],:] = 99 # assign values with fancy indexing
myarr

print '---'

myarr[:,[0,1]]
myarr[:,[-1, -2]]

print '---'

myarr[[0,1],[-3,1]] # values returned are those @ [0,-3] & [1,1]
# compare to
myarr[[0,1]][:,[-3,1]] 
# and see also
myarr[np.ix_([0,1],[-3,1])]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

array([[4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

array([[99, 99, 99, 99],
       [99, 99, 99, 99]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

---


array([[99, 99],
       [99, 99],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21],
       [24, 25],
       [28, 29]])

array([[99, 99],
       [99, 99],
       [11, 10],
       [15, 14],
       [19, 18],
       [23, 22],
       [27, 26],
       [31, 30]])

---


array([99, 99])

array([[99, 99],
       [99, 99]])

array([[99, 99],
       [99, 99]])

In [141]:
# ravel, flatten 
# ravel - returns a view when possible; is a library-level and array-level function
# flatten - always returns a copy; is an array-level function only

myarr = np.round(np.random.rand(12),2).reshape(4,3)
myarr

np.ravel(myarr)
r = myarr.ravel()
r
r.shape

r[[1,3,5,7]] = -99 # modified original array since r is a view
r
myarr

f = myarr.flatten()
f
f[[0,2,4]] = -88 # does not modify original array
f
myarr


array([[ 0.56,  0.89,  0.78],
       [ 0.79,  0.61,  0.7 ],
       [ 0.95,  0.94,  0.18],
       [ 0.07,  0.41,  0.48]])

array([ 0.56,  0.89,  0.78,  0.79,  0.61,  0.7 ,  0.95,  0.94,  0.18,
        0.07,  0.41,  0.48])

array([ 0.56,  0.89,  0.78,  0.79,  0.61,  0.7 ,  0.95,  0.94,  0.18,
        0.07,  0.41,  0.48])

(12,)

array([  5.60000000e-01,  -9.90000000e+01,   7.80000000e-01,
        -9.90000000e+01,   6.10000000e-01,  -9.90000000e+01,
         9.50000000e-01,  -9.90000000e+01,   1.80000000e-01,
         7.00000000e-02,   4.10000000e-01,   4.80000000e-01])

array([[  5.60000000e-01,  -9.90000000e+01,   7.80000000e-01],
       [ -9.90000000e+01,   6.10000000e-01,  -9.90000000e+01],
       [  9.50000000e-01,  -9.90000000e+01,   1.80000000e-01],
       [  7.00000000e-02,   4.10000000e-01,   4.80000000e-01]])

array([  5.60000000e-01,  -9.90000000e+01,   7.80000000e-01,
        -9.90000000e+01,   6.10000000e-01,  -9.90000000e+01,
         9.50000000e-01,  -9.90000000e+01,   1.80000000e-01,
         7.00000000e-02,   4.10000000e-01,   4.80000000e-01])

array([ -8.80000000e+01,  -9.90000000e+01,  -8.80000000e+01,
        -9.90000000e+01,  -8.80000000e+01,  -9.90000000e+01,
         9.50000000e-01,  -9.90000000e+01,   1.80000000e-01,
         7.00000000e-02,   4.10000000e-01,   4.80000000e-01])

array([[  5.60000000e-01,  -9.90000000e+01,   7.80000000e-01],
       [ -9.90000000e+01,   6.10000000e-01,  -9.90000000e+01],
       [  9.50000000e-01,  -9.90000000e+01,   1.80000000e-01],
       [  7.00000000e-02,   4.10000000e-01,   4.80000000e-01]])

In [173]:
# stacking

myarr = np.arange(5)
myarr # row vector

np.vstack([myarr, myarr, myarr]) # row vector as rows of matrix

# row vector as columns of matrix
np.hstack([myarr, myarr, myarr])
np.hstack([myarr.T, myarr.T]) # transpose will not work to convert row vectors to column vectors
np.hstack([myarr.reshape(1,5), myarr.reshape(1,5)]) # reshape also will not work
np.hstack([myarr[:,np.newaxis], myarr[:,np.newaxis]]) # must use newaxis 

print '---'

myarr = np.arange(24).reshape(2,3,4)
myarr
myarr.shape

h = np.hstack([myarr, myarr])
h
h.shape

v = np.vstack([myarr, myarr])
v
v.shape

print '---'

c = np.concatenate([myarr, myarr], axis=0) # same as vstack
c
c.shape

c = np.concatenate([myarr, myarr], axis=1) # same as hstack
c
c.shape

c = np.concatenate([myarr, myarr], axis=2) # same as dstack
c
c.shape

d = np.dstack([myarr, myarr]) 
d 
d.shape


array([0, 1, 2, 3, 4])

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]])

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

---


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

(2, 3, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

(2, 6, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

(4, 3, 4)

---


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

(4, 3, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

(2, 6, 4)

array([[[ 0,  1,  2,  3,  0,  1,  2,  3],
        [ 4,  5,  6,  7,  4,  5,  6,  7],
        [ 8,  9, 10, 11,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 12, 13, 14, 15],
        [16, 17, 18, 19, 16, 17, 18, 19],
        [20, 21, 22, 23, 20, 21, 22, 23]]])

(2, 3, 8)

array([[[ 0,  1,  2,  3,  0,  1,  2,  3],
        [ 4,  5,  6,  7,  4,  5,  6,  7],
        [ 8,  9, 10, 11,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 12, 13, 14, 15],
        [16, 17, 18, 19, 16, 17, 18, 19],
        [20, 21, 22, 23, 20, 21, 22, 23]]])

(2, 3, 8)

In [10]:
# Transposing arrays
# all transposing return a view on the array and not a copy

myarr = np.arange(15).reshape(5,3)
myarr

myarr.transpose()
myarr.T

myarr.shape
myarr.T.shape

np.dot(myarr.T, myarr) # X'X

# swapaxes - both statements below are equivalent
myarr.swapaxes(0,1)
myarr.swapaxes(1,0)

myarr = np.arange(24).reshape(2,3,4)
myarr
myarr.swapaxes(0,2)

myarr.transpose(4,2,3)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

(5, 3)

(3, 5)

array([[270, 300, 330],
       [300, 335, 370],
       [330, 370, 410]])

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

ValueError: invalid axis for this array

In [95]:
# Meshgrid

x = np.linspace(1,4, num=4)
y = np.linspace(11,15, num=6)
x
y

x_coords, y_coords = np.meshgrid(x,y)
x_coords
y_coords

print '-'

a = x_coords + y_coords
(x_coords + y_coords)**2

print '-'

x_coords, y_coords = np.meshgrid(x,y, indexing='ij')
x_coords
y_coords



array([ 1.,  2.,  3.,  4.])

array([ 11. ,  11.8,  12.6,  13.4,  14.2,  15. ])

array([[ 1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.]])

array([[ 11. ,  11. ,  11. ,  11. ],
       [ 11.8,  11.8,  11.8,  11.8],
       [ 12.6,  12.6,  12.6,  12.6],
       [ 13.4,  13.4,  13.4,  13.4],
       [ 14.2,  14.2,  14.2,  14.2],
       [ 15. ,  15. ,  15. ,  15. ]])

-


array([[ 144.  ,  169.  ,  196.  ,  225.  ],
       [ 163.84,  190.44,  219.04,  249.64],
       [ 184.96,  213.16,  243.36,  275.56],
       [ 207.36,  237.16,  268.96,  302.76],
       [ 231.04,  262.44,  295.84,  331.24],
       [ 256.  ,  289.  ,  324.  ,  361.  ]])

-


array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.]])

array([[ 11. ,  11.8,  12.6,  13.4,  14.2,  15. ],
       [ 11. ,  11.8,  12.6,  13.4,  14.2,  15. ],
       [ 11. ,  11.8,  12.6,  13.4,  14.2,  15. ],
       [ 11. ,  11.8,  12.6,  13.4,  14.2,  15. ]])

---


array([[[0, 0],
        [1, 1]],

       [[0, 1],
        [0, 1]]])

In [195]:
# where

myarr = np.round(np.random.randn(4,4),2)
myarr

np.where(myarr < 0, 0, 99) # replace -ve values with 0 and non-neg values with 99
np.where(myarr < 0, 0, myarr) # replace -ve values with 0; leave non-neg values as-is

print '---'

# select
np.select([myarr<0, myarr>= 0], [0, myarr]) # same as using where above
np.select([myarr<0, myarr<1, myarr>= 1], [0, 1, myarr]) # same as using where above

print '---'

# choose 
np.choose([0,0,1,1,2,2], [11,12,13])

# nonzero
np.nonzero(myarr)
myarr[np.nonzero(np.zeros_like(myarr))]
myarr[np.nonzero(np.ones_like(myarr))]


array([[-1.68, -0.4 ,  0.14, -0.59],
       [ 1.79,  0.52, -0.87,  0.88],
       [-0.51, -1.01, -0.13, -0.19],
       [-0.41,  0.01, -0.51, -0.78]])

array([[ 0,  0, 99,  0],
       [99, 99,  0, 99],
       [ 0,  0,  0,  0],
       [ 0, 99,  0,  0]])

array([[ 0.  ,  0.  ,  0.14,  0.  ],
       [ 1.79,  0.52,  0.  ,  0.88],
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.01,  0.  ,  0.  ]])

---


array([[ 0.  ,  0.  ,  0.14,  0.  ],
       [ 1.79,  0.52,  0.  ,  0.88],
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.01,  0.  ,  0.  ]])

array([[ 0.  ,  0.  ,  1.  ,  0.  ],
       [ 1.79,  1.  ,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ]])

---


array([11, 11, 12, 12, 13, 13])

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))

array([], dtype=float64)

array([-1.68, -0.4 ,  0.14, -0.59,  1.79,  0.52, -0.87,  0.88, -0.51,
       -1.01, -0.13, -0.19, -0.41,  0.01, -0.51, -0.78])

In [13]:
# Random walks

print 'Single random walk'
walk = np.random.randint(0,2,1000)
walk = np.where(walk>0, 1, -1)
walk = walk.cumsum()

# plt.plot(walk);

walk.min()
walk.max()

# time for walk to exceed 10 from origin
(abs(walk)>10).argmax()

print '---'
print 'Multiple random walks'

steps = np.random.randn(100, 1000)
steps.shape
walk = steps.cumsum(axis=1)
walk.shape

walk
(walk > 10).any(1) # get all walks that cross +10
(walk > 10).any(1).sum() # how many walks cross +10?

crossing_times = walk[(walk > 10).any(1)].argmax(axis=1) # when does each walk that cross +10 cross +10?
crossing_times
crossing_times.mean()


Single random walk


-7

34

178

---
Multiple random walks


(100, 1000)

(100, 1000)

array([[  0.31802541,  -1.33957098,  -0.21431708, ..., -51.3492799 ,
        -50.85109417, -51.28332017],
       [  0.77011331,   0.60729373,  -0.80297991, ..., -20.64113584,
        -21.89226311, -21.94830822],
       [ -1.09356511,  -1.72763304,  -2.08986624, ...,  39.43550392,
         38.70066617,  38.51549964],
       ..., 
       [ -0.67689754,   1.28182846,   0.76756105, ...,  46.18079709,
         46.16942317,  46.26582822],
       [ -1.79755416,  -2.65035402,  -2.10296836, ...,  -8.74279536,
         -7.36441623,  -8.05095313],
       [  0.22783953,  -2.26614744,  -4.4429862 , ...,   4.36115223,
          4.03182597,   3.89883578]])

array([False, False,  True,  True, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False,  True,  True,  True,
       False, False,  True,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True, False,  True,  True, False,  True, False,  True,
        True,  True,  True,  True,  True, False, False,  True, False,  True], dtype=bool)

75

array([786, 949, 822, 909, 993, 862, 956, 171, 499, 691, 557,  50, 923,
       601, 771, 227, 300, 957, 408, 998, 918, 677, 994, 261, 905, 619,
       880, 351, 983, 679, 877, 891, 914, 940,  88,  69, 614, 840, 985,
       155, 169, 760, 558, 632, 618, 960, 510, 242, 997, 700, 999, 809,
       463, 252, 989, 995, 654, 961, 932, 304, 790, 404, 696, 578, 639,
       608, 965, 662, 195, 970, 652, 939, 207, 985, 356])

669.60000000000002

In [204]:
# dot

a = np.round(np.linspace(0,1,10),2).reshape(5,2)
a

b = np.round(np.linspace(0,1,10),2).reshape(2,5)
b

a.dot(b)
np.dot(b,a)

# ToDo


array([[ 0.  ,  0.11],
       [ 0.22,  0.33],
       [ 0.44,  0.56],
       [ 0.67,  0.78],
       [ 0.89,  1.  ]])

array([[ 0.  ,  0.11,  0.22,  0.33,  0.44],
       [ 0.56,  0.67,  0.78,  0.89,  1.  ]])

array([[ 0.0616,  0.0737,  0.0858,  0.0979,  0.11  ],
       [ 0.1848,  0.2453,  0.3058,  0.3663,  0.4268],
       [ 0.3136,  0.4236,  0.5336,  0.6436,  0.7536],
       [ 0.4368,  0.5963,  0.7558,  0.9153,  1.0748],
       [ 0.56  ,  0.7679,  0.9758,  1.1837,  1.3916]])

array([[ 0.7337,  0.8569],
       [ 1.9769,  2.4137]])