## Task
Explore sorting in NumPy

## Notebook summary
* `ndarray.sort` - sorts array in-place
* `np.sort` - makes a copy of array, then sorts
* Sort descending
* `argsort` - get indices in sorted order
* `lexsort` - sort multiple arrays together
* Other sorting algorithms - stable sort with with argsort + mergesort
* `searchsorted` - find elements in a sorted array

## References
* *Python for Data Analysis*, Wes McKinney, O'Reilly, 2012
* *Numerical Python*, Robert Johansson, APress, 2015


In [1]:
# display output from all cmds just like Python shell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import platform
print 'python.version = ', platform.python_version()
import IPython
print 'ipython.version =', IPython.version_info

import numpy as np
print 'numpy.version = ', np.__version__


python.version =  2.7.10
ipython.version = (5, 1, 0, '')
numpy.version =  1.11.3


In [2]:
# ndarray.sort

# Sort copy of array
arr = np.arange(20) # 1:20 generated in asc order

arr = arr[np.random.permutation(20)].reshape(4,5) # shuffle array elements & reshape
arr

arr1 = arr.copy()
arr1.sort() # by default, sorts along last axis (here: within a row; each row separately)
arr1

arr1.sort(axis=0) # sort in-place, each column independently; sort() returns None
arr1

print '---'

# Sorting array views sorts associated elements in underlying array
arr[:,0] # get view of 1st column in array
arr[:,0].sort() # udnerlying array is modified
arr


array([[ 0,  8,  7,  2, 16],
       [ 9, 17, 12,  5, 18],
       [10, 11,  3, 14, 13],
       [ 1, 19,  4,  6, 15]])

array([[ 0,  2,  7,  8, 16],
       [ 5,  9, 12, 17, 18],
       [ 3, 10, 11, 13, 14],
       [ 1,  4,  6, 15, 19]])

array([[ 0,  2,  6,  8, 14],
       [ 1,  4,  7, 13, 16],
       [ 3,  9, 11, 15, 18],
       [ 5, 10, 12, 17, 19]])

---


array([ 0,  9, 10,  1])

array([[ 0,  8,  7,  2, 16],
       [ 1, 17, 12,  5, 18],
       [ 9, 11,  3, 14, 13],
       [10, 19,  4,  6, 15]])

In [3]:
# np.sort - same params as ndarray.sort

arr = np.arange(20)[np.random.permutation(20)].reshape(4,5) # generate 1:20 in random order
print 'Original array'
arr

print 'Sort within rows'
np.sort(arr) # copy array, then sort asc within each row

print 'Sort within rows descending'
np.sort(arr)[:,::-1]

print '---'

print 'Sort within columns'
np.sort(arr, axis=0)

print 'Sort within columns descending'
print 'ToDo'

print '---'

print 'Original array'
arr # original array is not sorted


Original array


array([[15, 13, 17, 10, 12],
       [19,  3, 14,  1,  2],
       [ 7,  5,  4,  0, 16],
       [18, 11,  8,  9,  6]])

Sort within rows


array([[10, 12, 13, 15, 17],
       [ 1,  2,  3, 14, 19],
       [ 0,  4,  5,  7, 16],
       [ 6,  8,  9, 11, 18]])

Sort within rows descending


array([[17, 15, 13, 12, 10],
       [19, 14,  3,  2,  1],
       [16,  7,  5,  4,  0],
       [18, 11,  9,  8,  6]])

---
Sort within columns


array([[ 7,  3,  4,  0,  2],
       [15,  5,  8,  1,  6],
       [18, 11, 14,  9, 12],
       [19, 13, 17, 10, 16]])

Sort within columns descending
ToDo
---
Original array


array([[15, 13, 17, 10, 12],
       [19,  3, 14,  1,  2],
       [ 7,  5,  4,  0, 16],
       [18, 11,  8,  9,  6]])

In [4]:
# argsort

arr = np.round(np.random.randn(10),3)
arr
arr.argsort() # indices of sorted array
arr[arr.argsort()]

print '---'

n = 20
r,c=(4,5)
arr = np.arange(n)[np.random.permutation(n)].reshape(r,c)

print 'Original array'
arr

print 'Indices in sorted array'
arr.argsort() # indices of array sorted by last axis (here: within each row)
arr[0].argsort() # indices of sorted 1st row 

print 'Sort by order of sorted 1st row; other rows won\'t be sorted within row'
arr[:,arr[0].argsort()]


array([-0.721, -0.667, -0.619,  0.072,  0.405,  0.153, -0.261,  1.055,
        0.015, -0.635])

array([0, 1, 9, 2, 6, 8, 3, 5, 4, 7])

array([-0.721, -0.667, -0.635, -0.619, -0.261,  0.015,  0.072,  0.153,
        0.405,  1.055])

---
Original array


array([[11,  1,  6, 12,  0],
       [ 8, 14, 13,  7, 18],
       [ 9, 17,  4,  2, 10],
       [19, 16, 15,  5,  3]])

Indices in sorted array


array([[4, 1, 2, 0, 3],
       [3, 0, 2, 1, 4],
       [3, 2, 0, 4, 1],
       [4, 3, 2, 1, 0]])

array([4, 1, 2, 0, 3])

Sort by order of sorted 1st row; other rows won't be sorted within row


array([[ 0,  1,  6, 11, 12],
       [18, 14, 13,  8,  7],
       [10, 17,  4,  9,  2],
       [ 3, 16, 15, 19,  5]])

In [5]:
# lexsort - sort multiple columns together

print 'Original array'
n = 10
arr1 = np.arange(n)[np.random.permutation(n)]
arr1
arr2 = np.arange(n)[np.random.permutation(n)] + 10
arr2

idx = np.lexsort([arr1, arr2]) # sort by arr2 first and then arr1
[(arr1[i], arr2[i]) for i in idx]

idx = np.lexsort([arr2, arr1]) # sort by arr1 first and then arr1
[(arr1[i], arr2[i]) for i in idx]

print '---'
print 'lexsort strings'
arr1 = np.array(['A']*3 + ['B']*3)
arr1
arr2 = np.array(['X','Y','Z']*2)
arr2

idx = np.lexsort([arr2, arr1])
[(arr1[i], arr2[i]) for i in idx]


Original array


array([2, 4, 6, 1, 3, 7, 9, 0, 8, 5])

array([12, 13, 14, 16, 15, 10, 17, 18, 19, 11])

[(7, 10),
 (5, 11),
 (2, 12),
 (4, 13),
 (6, 14),
 (3, 15),
 (1, 16),
 (9, 17),
 (0, 18),
 (8, 19)]

[(0, 18),
 (1, 16),
 (2, 12),
 (3, 15),
 (4, 13),
 (5, 11),
 (6, 14),
 (7, 10),
 (8, 19),
 (9, 17)]

---
lexsort strings


array(['A', 'A', 'A', 'B', 'B', 'B'], 
      dtype='|S1')

array(['X', 'Y', 'Z', 'X', 'Y', 'Z'], 
      dtype='|S1')

[('A', 'X'), ('A', 'Y'), ('A', 'Z'), ('B', 'X'), ('B', 'Y'), ('B', 'Z')]

In [6]:
# argsort with mergesort
# - only stable sorting algorithm available in numpy
# - cannot sort objects in arrays (dtype=object)


arr = np.array(['3;1', '1;1', '2;1', '1;2', '4;2', '2;3', '3;2'])
arr
np.sort(arr)

keys = np.array([3,1,2,1,4,2,3])
idx = keys.argsort(kind='mergesort')
idx
arr[idx]


array(['3;1', '1;1', '2;1', '1;2', '4;2', '2;3', '3;2'], 
      dtype='|S3')

array(['1;1', '1;2', '2;1', '2;3', '3;1', '3;2', '4;2'], 
      dtype='|S3')

array([1, 3, 2, 5, 0, 6, 4])

array(['1;1', '1;2', '2;1', '2;3', '3;1', '3;2', '4;2'], 
      dtype='|S3')

In [10]:
# searchsorted - find indices where new items must be inserted in a sorted array to maintain sorted-ness

arr = np.arange(10)
arr

arr.searchsorted(0) # return index to left of existing 0
arr.searchsorted(10)
arr.searchsorted([1,2,1,2])


# Bin data using searchsorted
values = np.round(np.random.randn(50),2)
values
values.min(), values.max()

bins = np.array([-5,-1,0,1,5])

bins.searchsorted(values)

# compare with np.digitize
np.digitize(values, bins)

# verify both methods generate the same result
np.array_equal(bins.searchsorted(values), np.digitize(values, bins))


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

0

10

array([1, 2, 1, 2])

array([-0.49,  0.34,  1.59,  0.46, -1.57, -0.51, -1.21, -0.17,  0.25,
        0.15,  0.43, -0.81,  0.68,  2.3 ,  1.62, -0.95, -0.98,  2.72,
       -0.62, -1.27,  1.07,  1.69,  1.05,  2.99,  1.31, -0.59,  0.68,
       -1.67,  0.14,  0.9 , -0.85,  0.69,  1.04,  1.19, -0.03, -2.21,
       -1.1 , -0.45,  0.07, -0.26,  1.77, -0.6 , -0.13, -0.04, -0.33,
       -0.21,  0.06, -0.3 ,  0.86,  1.21])

(-2.21, 2.9900000000000002)

array([2, 3, 4, 3, 1, 2, 1, 2, 3, 3, 3, 2, 3, 4, 4, 2, 2, 4, 2, 1, 4, 4, 4,
       4, 4, 2, 3, 1, 3, 3, 2, 3, 4, 4, 2, 1, 1, 2, 3, 2, 4, 2, 2, 2, 2, 2,
       3, 2, 3, 4])

array([2, 3, 4, 3, 1, 2, 1, 2, 3, 3, 3, 2, 3, 4, 4, 2, 2, 4, 2, 1, 4, 4, 4,
       4, 4, 2, 3, 1, 3, 3, 2, 3, 4, 4, 2, 1, 1, 2, 3, 2, 4, 2, 2, 2, 2, 2,
       3, 2, 3, 4])

True