## Task
Explore random number generation in NumPy

## Notebook Summary
* Random walks

## References
* *Python for Data Analysis*, Wes McKinney, O'Reilly, 2012
* *Numerical Python*, Robert Johansson, APress, 2015
* *Python Data Science Handbook*, Jake VanderPlas, O'Reilly, 2016


In [2]:
# display output from all cmds just like Python shell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import platform
print 'python.version = ', platform.python_version()
import IPython
print 'ipython.version =', IPython.version_info

import numpy as np
print 'numpy.version = ', np.__version__


python.version =  2.7.10
ipython.version = (5, 1, 0, '')
numpy.version =  1.11.3


In [3]:
# Random walks

print 'Single random walk'
walk = np.random.randint(0,2,1000)
walk = np.where(walk>0, 1, -1)
walk = walk.cumsum()

# plt.plot(walk);

walk.min()
walk.max()

# time for walk to exceed 10 from origin
(abs(walk)>10).argmax()

print '---'
print 'Multiple random walks'

steps = np.random.randn(100, 1000)
steps.shape
walk = steps.cumsum(axis=1)
walk.shape

walk
(walk > 10).any(1) # get all walks that cross +10
(walk > 10).any(1).sum() # how many walks cross +10?

crossing_times = walk[(walk > 10).any(1)].argmax(axis=1) # when does each walk that cross +10 cross +10?
crossing_times
crossing_times.mean()


Single random walk


-48

3

98

---
Multiple random walks


(100, 1000)

(100, 1000)

array([[ -1.75090308e+00,  -1.63058808e+00,  -1.11245831e-02, ...,
         -1.80377062e+01,  -1.80133240e+01,  -1.76645308e+01],
       [ -1.39164510e-02,   9.73018315e-01,   2.10742618e+00, ...,
          2.75197777e+01,   2.84727032e+01,   2.76397340e+01],
       [  7.56829165e-01,   6.48223104e-01,  -4.98727943e-01, ...,
         -7.97490125e+00,  -8.39964355e+00,  -9.26446598e+00],
       ..., 
       [ -8.75788610e-01,  -1.77906777e+00,  -1.12859872e+00, ...,
         -3.75146106e+01,  -3.81272246e+01,  -3.83312244e+01],
       [  1.72527088e+00,   1.16505563e+00,   2.97493818e+00, ...,
          2.41798342e+01,   2.34959386e+01,   2.20775023e+01],
       [  5.21020445e-01,   9.99531401e-01,  -1.07626098e-01, ...,
          3.88409878e+01,   4.00980467e+01,   4.14098887e+01]])

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True, False,  True, False, False,  True,  True, False,  True,
        True, False,  True, False,  True,  True, False,  True,  True,
        True,  True,  True,  True, False,  True,  True, False, False,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False, False,
       False, False,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True, False,  True,  True, False,  True,  True], dtype=bool)

75

array([661, 444,  58, 335, 851, 476, 919, 434, 426, 308, 528, 923, 155,
       526, 393, 975, 373, 514, 909, 105, 721, 538, 403, 236, 205, 999,
       350, 296, 428,  28, 486, 486, 861, 806, 453, 184, 929, 724, 732,
       152, 639, 350, 966, 982, 708, 913, 502, 862, 147, 996, 996, 882,
       994, 351, 373, 947, 741, 233, 574, 187, 665, 471, 997, 729, 183,
       113, 685, 986, 206, 165, 938, 187, 966, 834, 801])

567.98666666666668