## Task
Explore random number generation in NumPy

## Notebook Summary
* `rand`
* `randn`
* `randint`
* `choice`
* `shuffle`
* `permutation`
* `gamma`
* `poisson`
* `seed`
* Random walks

## References
* *Python for Data Analysis*, Wes McKinney, O'Reilly, 2012
* *Numerical Python*, Robert Johansson, APress, 2015
* *Python Data Science Handbook*, Jake VanderPlas, O'Reilly, 2016


In [2]:
# display output from all cmds just like Python shell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import platform
print 'python.version = ', platform.python_version()
import IPython
print 'ipython.version =', IPython.version_info

import numpy as np
print 'numpy.version = ', np.__version__


python.version =  2.7.10
ipython.version = (5, 1, 0, '')
numpy.version =  1.11.3


In [18]:
# rand - Create array of given shape with random numbers in [0,1]

np.random.rand(10)
np.random.rand(4,2)
np.random.rand(2,3,4)

print 'Random numbers in [4,6]'
4 + 2*np.random.rand(10)

print 'mean (10000) = ', np.mean(4+2*np.random.rand(10000)) # (4+6)/2
print 'var (10000) = ', np.var(4+2*np.random.rand(10000)) # (1/12)(6-4)^2


array([ 0.68527978,  0.38675501,  0.12979784,  0.78103449,  0.47269334,
        0.29333284,  0.25124237,  0.23457237,  0.25320983,  0.74820916])

array([[ 0.20093211,  0.8917277 ],
       [ 0.32579079,  0.90018881],
       [ 0.83999556,  0.53446941],
       [ 0.10777899,  0.24352932]])

array([[[ 0.08103232,  0.5761672 ,  0.1677006 ,  0.53979708],
        [ 0.88857487,  0.68970079,  0.60344579,  0.92681365],
        [ 0.22432591,  0.58919888,  0.15620342,  0.67908012]],

       [[ 0.66533586,  0.59162164,  0.20062504,  0.44332842],
        [ 0.6761853 ,  0.304335  ,  0.65106719,  0.59270327],
        [ 0.44593167,  0.05757666,  0.97408014,  0.71598765]]])

Random numbers in [4,6]


array([ 5.50645713,  4.19624603,  4.05104358,  4.90076008,  5.70061338,
        5.28921037,  4.20464588,  4.97326536,  5.58194756,  4.56906826])

mean (10000) =  5.01124372424
var (10000) =  0.332024496684


In [19]:
# randn - Create array of given shape with random numbers from N(0,1)

np.random.randn(5)
np.random.randn(3,2)

temp = np.random.randn(10000)
print 'mean (10000) = ', np.mean(temp)
print 'var (10000) = ', np.var(temp)
print 'std (10000) = ', np.std(temp)


array([-1.50701753,  0.61812751, -0.58773453,  1.93087647, -1.42487689])

array([[ 1.22343589,  2.02868299],
       [-0.10849001,  0.99704455],
       [-1.71355775,  1.45763419]])

mean (10000) =  -0.00439901356092
var (10000) =  0.993428478441
std (10000) =  0.996708823299


In [29]:
# randint - Create array of given shape with random integers in [start, stop)

np.random.randint(low=0, high=2, size=20)
np.random.randint(low=0, high=10, size=(4,3,4))


array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1])

array([[[1, 3, 8, 0],
        [3, 2, 6, 4],
        [5, 0, 8, 1]],

       [[4, 8, 5, 3],
        [8, 2, 4, 9],
        [5, 8, 9, 4]],

       [[2, 4, 7, 2],
        [1, 4, 6, 5],
        [4, 6, 9, 7]],

       [[5, 3, 0, 7],
        [1, 4, 5, 8],
        [5, 4, 3, 4]]])

In [39]:
# choice - random sample from a 1d array

np.random.choice(range(10), size=15) # sample with replacement by default


array([5, 6, 3, 5, 2, 7, 6, 4, 9, 0, 6, 8, 6, 8, 2])

In [49]:
# shuffle - permute items in place

arr = np.arange(12)
print 'Before shuffle: ', arr
np.random.shuffle(arr)
print 'After shuffle: ', arr

# shuffle only shuffles along 1st axis (here: rows are moved around but columns are not)
print '\n-----'
arr = np.arange(12).reshape(6,2)
arr
np.random.shuffle(arr)
arr

print '\n-----'
arr = np.arange(24).reshape(4,2,3)
arr
np.random.shuffle(arr)
arr


Before shuffle:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
After shuffle:  [ 7  0 10  6 11  4  1  2  8  5  9  3]

-----


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

array([[ 4,  5],
       [10, 11],
       [ 2,  3],
       [ 6,  7],
       [ 8,  9],
       [ 0,  1]])


-----


array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

array([[[ 6,  7,  8],
        [ 9, 10, 11]],

       [[ 0,  1,  2],
        [ 3,  4,  5]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [58]:
# permutation - return a permuted range or array

np.random.permutation(5) # generates seq automatically

arr = np.round(np.random.rand(6),2)
arr
np.random.permutation(arr)

arr = np.arange(12).reshape(4,3)
arr
np.random.permutation(arr) # permute only along 1st axis (here: rows are shuffled but columns are not)


array([1, 2, 3, 4, 0])

array([ 0.29,  0.02,  0.34,  0.9 ,  0.38,  0.12])

array([ 0.12,  0.38,  0.9 ,  0.29,  0.34,  0.02])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

array([[ 3,  4,  5],
       [ 9, 10, 11],
       [ 0,  1,  2],
       [ 6,  7,  8]])

In [63]:
# gamma

np.random.gamma(1,4)
np.random.gamma(2,3,size=(2,3))

s = np.random.gamma(2,3,size=10000)
print 'mean = ', np.mean(s) # mean = shape * scale
print 'var = ', np.var(s) # var = shape * (scale^2)


0.43202193039032655

array([[ 22.09919642,   5.43004342,   6.16639606],
       [  6.33749405,   3.38752609,   8.78035352]])

mean =  5.98433677897
var =  17.9156543681


In [66]:
# poisson

np.random.poisson(10, 10)

arr = np.random.poisson(3, 10000)
print 'mean = ', np.mean(arr) # mean = lambda
print 'var = ', np.var(arr) # var = lambda


array([19, 15,  9, 13,  9, 12, 15,  8, 11, 11])

mean =  3.0454
var =  2.97953884


In [67]:
# seed - set seed of RNG
np.random.seed(1234)


In [68]:
# Random walks

print 'Single random walk'
walk = np.random.randint(0,2,1000)
walk = np.where(walk>0, 1, -1)
walk = walk.cumsum()

# plt.plot(walk);

walk.min()
walk.max()

# time for walk to exceed 10 from origin
(abs(walk)>10).argmax()

print '---'
print 'Multiple random walks'

steps = np.random.randn(100, 1000)
steps.shape
walk = steps.cumsum(axis=1)
walk.shape

walk
(walk > 10).any(1) # get all walks that cross +10
(walk > 10).any(1).sum() # how many walks cross +10?

crossing_times = walk[(walk > 10).any(1)].argmax(axis=1) # when does each walk that cross +10 cross +10?
crossing_times
crossing_times.mean()


Single random walk


-9

60

298

---
Multiple random walks


(100, 1000)

(100, 1000)

array([[  0.33250662,   0.86145103,  -0.25906996, ...,   2.78357118,
          2.46428059,   3.41281484],
       [ -0.53969804,  -0.83603432,  -0.9080009 , ...,  48.35592745,
         48.64769692,  48.90149869],
       [ -0.58068658,  -0.79373792,  -2.48054905, ...,  29.08755196,
         28.95800264,  31.18961975],
       ..., 
       [  0.39634224,   0.8298613 ,   1.70357966, ...,   9.76451616,
         10.60776335,   8.89954917],
       [ -0.16167694,  -0.29715851,  -1.07924155, ...,  18.86350067,
         19.34341387,  20.14712186],
       [  0.66286232,   0.58815452,   1.07282867, ...,  10.7144828 ,
         10.3109053 ,   9.85833362]])

array([False,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True,  True,
       False,  True,  True,  True, False,  True,  True, False,  True,
       False,  True,  True, False,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False,  True,  True, False,  True,  True,  True,  True,
        True, False,  True, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True, False, False,
        True,  True,  True, False,  True,  True,  True,  True,  True,  True], dtype=bool)

75

array([990, 147, 738, 826, 871,  91, 998, 429, 425, 728, 722, 280, 487,
       608,  39, 870, 986, 369, 630, 313, 870, 722, 999, 146, 956,  80,
       468, 247, 989, 857, 270, 871, 693, 857, 900, 538,  73, 740,  66,
       808, 985, 502, 293, 469, 110, 569, 499, 999, 683, 999, 890,  77,
       977, 334, 189, 962, 106, 978, 497, 325, 604, 670, 801, 526, 947,
       393, 690, 991, 265, 967, 969, 174, 359, 748, 726])

599.60000000000002