## Task
Explore array creation in NumPy

## Notebook Summary
* `array`, 
* `asarray`
---
* `zeros`
* `ones` 
* `full` 
* `fill` 
* `empty`
* `eye`
* `identity`
* `diag`
---
* `arange`
* `linspace`
* `logspace`
* `fromfunction`
* `meshgrid`

## References
* *Python for Data Analysis*, Wes McKinney, O'Reilly, 2012
* *Numerical Python*, Robert Johansson, APress, 2015
* *Python Data Science Handbook*, Jake VanderPlas, O'Reilly, 2016


In [1]:
# display output from all cmds just like Python shell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import platform
print 'python.version = ', platform.python_version()
import IPython
print 'ipython.version =', IPython.version_info

import numpy as np
print 'numpy.version = ', np.__version__


python.version =  2.7.10
ipython.version = (5, 1, 0, '')
numpy.version =  1.11.3


In [21]:
# Creating arrays from lists using array() & asarray()

print '----- Create 1d array from list'
mylist = [1,2,3,4]
myarr = np.array(mylist) 
myarr

print '----- Create 2d array from list of lists'
myarr = np.array([[5.1,6.2],[7.3,8.4]])
myarr
myarr.dtype

print '----- Create 2d array from array & update'
myarr2 = np.array(myarr) # copy=True by default; else copy made only if necessary
myarr2[0,1] = 999
myarr2
print 'myarr is myarr2 = ', myarr is myarr2

print '----- Array attributes'
myarr = np.array([[1,2,3],[4,5,6],[7,8,9]])
myarr
print 'ndim={}, shape={}, size={}, dtype={}'.format(myarr.ndim, myarr.shape, myarr.size, myarr.dtype)
print [attr for attr in dir(myarr) if not attr.startswith('_')]

print ''
print '----- Change array dtype'
print 'float: \n', myarr.astype(float)
print 'str: \n', myarr.astype(str)
print 'original: \n', myarr


----- Create 1d array from list


array([1, 2, 3, 4])

----- Create 2d array from list of lists


array([[ 5.1,  6.2],
       [ 7.3,  8.4]])

dtype('float64')

----- Create 2d array from array & update


array([[   5.1,  999. ],
       [   7.3,    8.4]])

myarr is myarr2 =  False
----- Array attributes


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

ndim=2, shape=(3, 3), size=9, dtype=int64
['T', 'all', 'any', 'argmax', 'argmin', 'argpartition', 'argsort', 'astype', 'base', 'byteswap', 'choose', 'clip', 'compress', 'conj', 'conjugate', 'copy', 'ctypes', 'cumprod', 'cumsum', 'data', 'diagonal', 'dot', 'dtype', 'dump', 'dumps', 'fill', 'flags', 'flat', 'flatten', 'getfield', 'imag', 'item', 'itemset', 'itemsize', 'max', 'mean', 'min', 'nbytes', 'ndim', 'newbyteorder', 'nonzero', 'partition', 'prod', 'ptp', 'put', 'ravel', 'real', 'repeat', 'reshape', 'resize', 'round', 'searchsorted', 'setfield', 'setflags', 'shape', 'size', 'sort', 'squeeze', 'std', 'strides', 'sum', 'swapaxes', 'take', 'tobytes', 'tofile', 'tolist', 'tostring', 'trace', 'transpose', 'var', 'view']

----- Change array dtype
float: 
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]
str: 
[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]
original: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# asarray

myarr = np.asarray([1, 2, 3,4]) # no copy if input is an ndarray 
myarr

myarr2 = np.asarray(myarr)
print 'myarr is myarr2 = ', myarr is myarr2 # verify that both array variables point to the same object


array([1, 2, 3, 4])

myarr is myarr2 =  True


In [32]:
# zeros

np.zeros(1, dtype='complex')
np.zeros([2,3,2])
np.zeros_like(myarr)


array([ 0.+0.j])

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
# ones

np.ones(2)
np.ones([1,2,3], dtype='int')
np.ones_like(myarr)


array([ 1.,  1.])

array([[[1, 1, 1],
        [1, 1, 1]]])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [24]:
# full

np.full((1,1), 9.9)
np.full([3,2], 'a', dtype='str')
np.full_like(myarr, 99, dtype='int')


array([[ 9.9]])

array([['a', 'a'],
       ['a', 'a'],
       ['a', 'a']], 
      dtype='|S1')

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [25]:
# fill

myarr2 = np.zeros([2,3])
myarr2
myarr2.fill(-50)
myarr2


array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

array([[-50., -50., -50.],
       [-50., -50., -50.]])

In [28]:
# empty

np.empty(3)
np.empty([2,3], dtype=int)
np.empty_like(myarr)


array([  4.94065646e-324,   9.88131292e-324,   1.48219694e-323])

array([[0, 0, 0],
       [0, 0, 0]])

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [29]:
# eye, identity

np.eye(4)
np.eye(4,3, k=-1)
np.identity(4)


array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

array([[ 0.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [36]:
# diag

np.diag([1,2,3])
np.diag(np.arange(6))

np.diag(np.arange(6))[::2] # get every other row
np.diag(np.arange(6))[:,::2] # get every other column


array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 0, 4, 0]])

array([[0, 0, 0],
       [0, 0, 0],
       [0, 2, 0],
       [0, 0, 0],
       [0, 0, 4],
       [0, 0, 0]])

In [42]:
# arange - evenly spaced points in an interval

np.arange(0)
np.arange(1)
np.arange(5)
np.arange(1,20,3)
np.arange(1.5,5.2,0.333)


array([], dtype=int64)

array([0])

array([0, 1, 2, 3, 4])

array([ 1,  4,  7, 10, 13, 16, 19])

array([ 1.5  ,  1.833,  2.166,  2.499,  2.832,  3.165,  3.498,  3.831,
        4.164,  4.497,  4.83 ,  5.163])

In [37]:
# linspace - evenly spaced points in an interval

np.linspace(0,1) # return 50 pts by default
np.linspace(start=1, stop=10, num=10, dtype='int')
np.linspace(2,4, num=20, endpoint=False, retstep=True)
np.linspace(2,4, num=20, endpoint=True, retstep=True)


array([ 0.        ,  0.02040816,  0.04081633,  0.06122449,  0.08163265,
        0.10204082,  0.12244898,  0.14285714,  0.16326531,  0.18367347,
        0.20408163,  0.2244898 ,  0.24489796,  0.26530612,  0.28571429,
        0.30612245,  0.32653061,  0.34693878,  0.36734694,  0.3877551 ,
        0.40816327,  0.42857143,  0.44897959,  0.46938776,  0.48979592,
        0.51020408,  0.53061224,  0.55102041,  0.57142857,  0.59183673,
        0.6122449 ,  0.63265306,  0.65306122,  0.67346939,  0.69387755,
        0.71428571,  0.73469388,  0.75510204,  0.7755102 ,  0.79591837,
        0.81632653,  0.83673469,  0.85714286,  0.87755102,  0.89795918,
        0.91836735,  0.93877551,  0.95918367,  0.97959184,  1.        ])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

(array([ 2. ,  2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,
         3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9]), 0.1)

(array([ 2.        ,  2.10526316,  2.21052632,  2.31578947,  2.42105263,
         2.52631579,  2.63157895,  2.73684211,  2.84210526,  2.94736842,
         3.05263158,  3.15789474,  3.26315789,  3.36842105,  3.47368421,
         3.57894737,  3.68421053,  3.78947368,  3.89473684,  4.        ]),
 0.10526315789473684)

In [43]:
# logspace

np.logspace(1,2) # return 50 pts by default with base=10
np.logspace(1,2).shape

np.logspace(1,2, num=10) # base=10
np.logspace(1,2, num=10, base=np.exp(1)) # base=e
np.logspace(1,2, num=10, base=2)


array([  10.        ,   10.48113134,   10.98541142,   11.51395399,
         12.06792641,   12.64855217,   13.25711366,   13.89495494,
         14.56348478,   15.26417967,   15.9985872 ,   16.76832937,
         17.57510625,   18.42069969,   19.30697729,   20.23589648,
         21.20950888,   22.22996483,   23.29951811,   24.42053095,
         25.59547923,   26.82695795,   28.11768698,   29.47051703,
         30.88843596,   32.37457543,   33.93221772,   35.56480306,
         37.2759372 ,   39.06939937,   40.94915062,   42.9193426 ,
         44.98432669,   47.14866363,   49.41713361,   51.79474679,
         54.28675439,   56.89866029,   59.63623317,   62.50551925,
         65.51285569,   68.6648845 ,   71.9685673 ,   75.43120063,
         79.06043211,   82.86427729,   86.85113738,   91.0298178 ,
         95.40954763,  100.        ])

(50,)

array([  10.        ,   12.91549665,   16.68100537,   21.5443469 ,
         27.82559402,   35.93813664,   46.41588834,   59.94842503,
         77.42636827,  100.        ])

array([ 2.71828183,  3.03773178,  3.39472319,  3.79366789,  4.23949621,
        4.73771786,  5.29449005,  5.91669359,  6.61201791,  7.3890561 ])

array([ 2.        ,  2.16011948,  2.33305808,  2.5198421 ,  2.72158   ,
        2.93946898,  3.1748021 ,  3.42897593,  3.70349885,  4.        ])

In [44]:
# fromfunction - from function at each coordinate

f = lambda x,y: np.round(np.sin(x+y),2)
np.fromfunction(f, (3,3))


array([[ 0.  ,  0.84,  0.91],
       [ 0.84,  0.91,  0.14],
       [ 0.91,  0.14, -0.76]])

In [2]:
# Meshgrid

x = np.linspace(1,4, num=4)
y = np.linspace(11,15, num=6)
x
y

x_coords, y_coords = np.meshgrid(x,y)
x_coords
y_coords

print '-'

a = x_coords + y_coords
(x_coords + y_coords)**2

print '-'

x_coords, y_coords = np.meshgrid(x,y, indexing='ij')
x_coords
y_coords


array([ 1.,  2.,  3.,  4.])

array([ 11. ,  11.8,  12.6,  13.4,  14.2,  15. ])

array([[ 1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.]])

array([[ 11. ,  11. ,  11. ,  11. ],
       [ 11.8,  11.8,  11.8,  11.8],
       [ 12.6,  12.6,  12.6,  12.6],
       [ 13.4,  13.4,  13.4,  13.4],
       [ 14.2,  14.2,  14.2,  14.2],
       [ 15. ,  15. ,  15. ,  15. ]])

-


array([[ 144.  ,  169.  ,  196.  ,  225.  ],
       [ 163.84,  190.44,  219.04,  249.64],
       [ 184.96,  213.16,  243.36,  275.56],
       [ 207.36,  237.16,  268.96,  302.76],
       [ 231.04,  262.44,  295.84,  331.24],
       [ 256.  ,  289.  ,  324.  ,  361.  ]])

-


array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.]])

array([[ 11. ,  11.8,  12.6,  13.4,  14.2,  15. ],
       [ 11. ,  11.8,  12.6,  13.4,  14.2,  15. ],
       [ 11. ,  11.8,  12.6,  13.4,  14.2,  15. ],
       [ 11. ,  11.8,  12.6,  13.4,  14.2,  15. ]])