## Summary
My solutions to [100 Numpy exercises](https://github.com/rougier/numpy-100/blob/master/100%20Numpy%20exercises%20no%20solution.md)


In [2]:
# display output from all cmds just like Python shell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import platform
print 'python.version = ', platform.python_version()
import IPython
print 'ipython.version =', IPython.version_info


python.version =  2.7.10
ipython.version = (5, 1, 0, '')


In [3]:
# 1. Import the numpy package under the name np
import numpy as np

# 2. Print the numpy version and the configuration
print 'numpy.version = ', np.__version__
print np.show_config() # ToDo: need to use ATLAS or Intel MKL for better performance


numpy.version =  1.11.2
lapack_opt_info:
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    extra_compile_args = ['-msse3']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
openblas_lapack_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
blas_opt_info:
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
atlas_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
None


In [44]:
# 3. Create a null vector of size 10
arr = np.array([None]*10)
arr

# 4. How to find the memory size of any array
arr.size
np.array([1,2]).size

# 5. How to get the documentation of the numpy add function from the command line
# np.add? - this works in Jupyter only
help(np.add) # works in python cmd line interpreter


array([None, None, None, None, None, None, None, None, None, None], dtype=object)

10

2

Help on ufunc object:

add = class ufunc(__builtin__.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use np.info().  For
 |  example, np.info(np.sin).  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the "ufuncs.rst"
 |  file in the NumPy reference guide.
 |  
 |  Unary ufuncs:
 |  =============
 |  
 |  op(X, out=None)
 |  Apply op to X elementwise
 |  
 |  Parameters
 |  ----------
 |  X : array_like
 |      Input array.
 |  out : array_like
 |      An array to store the output. Must be the same shape as `X`.
 |  
 |  Returns
 |  -------
 |  r : array_like
 |      `r` will have the same shape as `X`; if out is provided, `r`
 |      will be equal to out.
 |  
 |  Binary ufuncs:
 |  ==============
 |  
 |  op(X, Y,

array([None, None, None, None, 1, None, None, None, None, None], dtype=object)

In [78]:
# 6. Create a null vector of size 10 but the fifth value which is 1 
arr = np.array([None]*10)
arr[4] = 1
arr

# 7. Create a vector with values ranging from 10 to 49
arr = np.arange(10,50)
arr

# 8. Reverse a vector (first element becomes last) 
arr[::-1]

# 9. Create a 3x3 matrix with values ranging from 0 to 8
np.arange(0,9).reshape(3,3)

# 10. Find indices of non-zero elements from [1,2,0,0,4,0]
np.argwhere([1,2,0,0,4,0]) # returns ndarray
np.nonzero([1,2,0,0,4,0]) # returns tuple of arrays


array([None, None, None, None, 1, None, None, None, None, None], dtype=object)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

numpy.ndarray

(array([0, 1, 4]),)

In [22]:
# 11. Create a 3x3 identity matrix
np.eye(3)
np.identity(3)

# 12. Create a 3x3x3 array with random values
np.random.rand(27).reshape(3,3,3)

# 13. Create a 10x10 array with random values and find the minimum and maximum values
arr = np.random.rand(100).reshape(10,10)
arr.max()
arr.min()

# 14. Create a random vector of size 30 and find the mean value
np.random.rand(30).mean()

# 15. Create a 2d array with 1 on the border and 0 inside
arr = np.zeros([4,4])
arr[0] = 1
arr[3] = 1
arr[:,0] = 1
arr[:,3] = 1
arr


array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

array([[[ 0.04797639,  0.13425173,  0.28840667],
        [ 0.9853933 ,  0.73430926,  0.90002302],
        [ 0.13854709,  0.85782543,  0.18841819]],

       [[ 0.03429664,  0.71652562,  0.17138524],
        [ 0.86965229,  0.30373033,  0.48799044],
        [ 0.02577925,  0.47829018,  0.74052442]],

       [[ 0.09787552,  0.31925765,  0.67040124],
        [ 0.54565978,  0.07545025,  0.25864969],
        [ 0.87733621,  0.62577547,  0.29596076]]])

0.99327400616267192

0.0082549127580675563

0.41825394838666868

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [74]:
# 16. How to add a border (filled with 0's) around an existing array?
arr = np.random.rand(8).reshape(4,2)
arr2 = np.zeros([6,4])
arr2[1:5,1:3] = arr
arr2

# 17. What is the result of the following expression?
# 0 * np.nan
# np.nan == np.nan
# np.inf > np.nan
# np.nan - np.nan
# 0.3 == 3 * 0.1

# np.nan
# False
# False
# np.nan
# True
# False but True for all non-multiples of 3

# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 
np.diag([1,2,3,4], k=-1)

# 19. Create a 8x8 matrix and fill it with a checkerboard pattern 
np.array(([1,0]*4 + [0,1]*4)*4).reshape(8,8)

# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
arr = np.arange(6*7*8).reshape(6,7,8)
arr[1,5,3]


array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.3661233 ,  0.94738923,  0.        ],
       [ 0.        ,  0.99630945,  0.40666524,  0.        ],
       [ 0.        ,  0.07567199,  0.84023556,  0.        ],
       [ 0.        ,  0.2406047 ,  0.26140021,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

99

In [127]:
# 21. Create a checkerboard 8x8 matrix using the tile function
a = np.array([1,0,0,1]).reshape(2,2)
np.tile(a, (4,4))

# 22. Normalize a 5x5 random matrix 
arr = np.random.rand(25).reshape(5,5)
arr
np.linalg.norm(arr)

# 23. Create a custom dtype that describes a color as four unisgned bytes (RGBA)
bt = np.dtype([('R','B'),('G','B'),('B','B'),('A','B')])
bt
np.array([(0,1,2,3), (4,5,6,7), (8,9,10,11)], dtype=bt)

# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
a = np.arange(15).reshape(5,3); a
b = np.random.rand(6).reshape(3,2); b
a.dot(b)

# 25. Given a 1D array, negate all elements which are between 3 and 8, in place.
a = np.arange(15)
np.random.shuffle(a)
a

a = np.where((a >= 3) & (a <= 8), -a, a)
a


array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

array([[ 0.60315274,  0.0380635 ,  0.33223186,  0.67304958,  0.73332293],
       [ 0.22145536,  0.20679843,  0.85154103,  0.08084479,  0.03134219],
       [ 0.67520196,  0.94452425,  0.55273284,  0.77708981,  0.6193497 ],
       [ 0.66868719,  0.29839634,  0.90005878,  0.23645013,  0.27824721],
       [ 0.04539785,  0.9814419 ,  0.11520801,  0.67718304,  0.96501934]])

2.9630806313509881

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

array([(0, 1, 2, 3), (4, 5, 6, 7), (8, 9, 10, 11)], 
      dtype=[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

array([[ 0.77798009,  0.81545144],
       [ 0.38008896,  0.06594572],
       [ 0.17435011,  0.42243357]])

array([[  0.72878919,   0.91081285],
       [  4.72604671,   4.82230505],
       [  8.72330422,   8.73379724],
       [ 12.72056173,  12.64528943],
       [ 16.71781925,  16.55678163]])

array([14,  4,  3,  2,  1,  6,  5, 13,  7, 11,  0, 10,  9,  8, 12])

array([14, -4, -3,  2,  1, -6, -5, 13, -7, 11,  0, 10,  9, -8, 12])

In [146]:
# 26. What is the output of the following script?
# print(sum(range(5),-1))
# from numpy import *
# print(sum(range(5),-1))

# 9 - sums everything, no additional params
# 10 - since np.sum takes -1 to be value for axis param and here it is 1st axis from the end

# 27. Consider an integer vector Z, which of these expressions are legal?
# Z**Z
# 2 << Z >> 2
# Z <- Z
# 1j*Z
# Z/1/1
# Z<Z>Z

Z = np.arange(3)
Z


# [1,1,4] - ** => raise to power element-wise => (0**0, 1**1, 2**2) and (anything)**0 = 1
# [0,1,2] - << = bitwise left shift, >> = bitwise right shift and using both operators results in the original array again
# [False, False, False] - <- is actually less than minus <something>, not an arrow operator like in R
# [0+0j,0+1j,0+2j] - 1j = the complex number (0 + 1j); the rest follows from element-wise multiplication of complex numbers
# [0,1,2] - divide by 1 twice returns input array
# [False, False, False] - since Z < Z is [False, False, False] and this > Z is also [False, False, False]


array([0, 1, 2])

array([False, False, False], dtype=bool)