## Task
Explore linear algebrea routines in NumPy

## Notebook Summary
* Matrix products - dot, inner, cross, outer, kron, einsum, tensordot

## References
* *Python for Data Analysis*, Wes McKinney, O'Reilly, 2012
* *Numerical Python*, Robert Johansson, APress, 2015
* *Python Data Science Handbook*, Jake VanderPlas, O'Reilly, 2016


In [2]:
# display output from all cmds just like Python shell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import platform
print 'python.version = ', platform.python_version()
import IPython
print 'ipython.version =', IPython.version_info

import numpy as np
print 'numpy.version = ', np.__version__


python.version =  2.7.10
ipython.version = (5, 1, 0, '')
numpy.version =  1.11.3


In [10]:
# dot

print '\n-----'
a = np.arange(1)
a
a.dot(a)

print '\n-----'
a = np.arange(2)
a, a.shape
a.dot(a)

print '\n-----'
a = np.round(np.linspace(0,1,10),2).reshape(5,2)
a
b = np.round(np.linspace(0,1,10),2).reshape(2,5)
b

a.dot(b) # ndarray method
np.dot(b,a) # np method

# ToDo



-----


array([0])

0


-----


(array([0, 1]), (2,))

1


-----


array([[ 0.  ,  0.11],
       [ 0.22,  0.33],
       [ 0.44,  0.56],
       [ 0.67,  0.78],
       [ 0.89,  1.  ]])

array([[ 0.  ,  0.11,  0.22,  0.33,  0.44],
       [ 0.56,  0.67,  0.78,  0.89,  1.  ]])

array([[ 0.0616,  0.0737,  0.0858,  0.0979,  0.11  ],
       [ 0.1848,  0.2453,  0.3058,  0.3663,  0.4268],
       [ 0.3136,  0.4236,  0.5336,  0.6436,  0.7536],
       [ 0.4368,  0.5963,  0.7558,  0.9153,  1.0748],
       [ 0.56  ,  0.7679,  0.9758,  1.1837,  1.3916]])

array([[ 0.7337,  0.8569],
       [ 1.9769,  2.4137]])