## Task
Explore ufuncs in NumPy

## Notebook Summary
* unuary ufuncs (single input)
* use `out` param to write output to specific memory location
* `reduce`, `accumulate`
* Broadcasting rules for binary ufuncs
* Generate histogram
* Custom ufuncs

## References
* *Python for Data Analysis*, Wes McKinney, O'Reilly, 2012
* *Numerical Python*, Robert Johansson, APress, 2015
* *Python Data Science Handbook*, Jake VanderPlas, O'Reilly, 2016


In [2]:
# display output from all cmds just like Python shell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import platform
print 'python.version = ', platform.python_version()
import IPython
print 'ipython.version =', IPython.version_info

import numpy as np
print 'numpy.version = ', np.__version__


python.version =  2.7.10
ipython.version = (5, 1, 0, '')
numpy.version =  1.11.3


In [11]:
# unary ufuncs

x = np.arange(10)
x

print '-----'
x**2 + x - 1
np.sin(x)**2 + np.cos(x)**2


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

-----


array([-1,  1,  5, 11, 19, 29, 41, 55, 71, 89])

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [15]:
# out - use out to save memory for computations on large arrays
x = np.arange(10)
x
y = np.zeros(10)
y

np.power(x, 2, out=y)
y


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

array([  0.,   1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81.])

array([  0.,   1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81.])

In [28]:
# reduce, accumulate

print '\n----- 1d array'
arr = np.arange(10)
arr
np.add.reduce(arr) # sum
np.add.accumulate(arr) # cumsum

print '\n----- 2d array'
arr = np.arange(12).reshape(4,3)
arr
np.add.reduce(arr) # default: reduce over axis=0
np.add.reduce(arr, axis=1)

np.add.accumulate(arr)
np.add.accumulate(arr, axis=1)



----- 1d array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

45

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])


----- 2d array


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

array([18, 22, 26])

array([ 3, 12, 21, 30])

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15],
       [18, 22, 26]])

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21],
       [ 9, 19, 30]])

### Broadcasting rules

Broadcasting is a set of rules to apply binary ufuncs to arrays of different sizes

1. If 2 arrays differ in the number of their dimensions, the shape of the array with fewer dimensions is padded with ones on the left side
2. If the shape of 3 arrays does not match in a dimension, the array with shape 1 in that dimension is extended to match the shape of the other array in that dimension
3. If sizes disagree in any dimension and neither is 1, then an error is raised

Ref: Section on Broadcasting in Chap 2 of *Python Data Science Handbook*

In [23]:
# Generate histogram

x = np.random.randint(low=1, high=100, size=100)
np.sort(x)
bin_edges = np.linspace(start=0, stop=100, num=11)
bin_edges
bins = np.searchsorted(bin_edges, x)
freq = np.zeros_like(bin_edges)

np.add.at(freq, bins, 1) # this is equivalent to: freq[bins] += 1
freq


array([ 1,  3,  5,  6,  9,  9,  9,  9, 11, 12, 13, 14, 15, 16, 17, 17, 18,
       18, 18, 23, 24, 24, 28, 28, 28, 29, 29, 30, 31, 32, 35, 35, 39, 39,
       42, 43, 45, 45, 46, 48, 49, 49, 50, 51, 55, 56, 56, 57, 58, 59, 60,
       60, 63, 63, 63, 63, 63, 65, 65, 68, 69, 70, 70, 71, 73, 73, 74, 75,
       76, 77, 77, 78, 79, 80, 81, 83, 84, 84, 85, 86, 87, 87, 89, 89, 89,
       90, 90, 92, 93, 93, 94, 94, 95, 96, 98, 98, 98, 99, 99, 99])

array([   0.,   10.,   20.,   30.,   40.,   50.,   60.,   70.,   80.,
         90.,  100.])

array([  0.,   8.,  11.,   9.,   6.,   9.,   9.,  11.,  11.,  13.,  13.])

In [9]:
# Custom ufuncs - can be slow compared to optimized ufuncs since 
# Python function has to be called for each value in array compared to calling C func on each value

def mult_elem(a, b):
    return a * b

f1 = np.frompyfunc(mult_elem, 2, 1)
a = f1([1,2,3], [4,5,6])
type(a)
a

print '\n-----'
f2 = np.vectorize(mult_elem, otypes=[np.int64])
b = f2([1,2,3], [4,5,6])
type(b)
b

arr = np.random.randn(1000)
%timeit f1(arr, arr)
%timeit f2(arr, arr)


numpy.ndarray

array([4, 10, 18], dtype=object)


-----


numpy.ndarray

array([ 4, 10, 18])

10000 loops, best of 3: 145 µs per loop
1000 loops, best of 3: 222 µs per loop
